plugins {
    id 'com.android.application' version '8.1.0'
}
android {
    namespace "com.martodosko.wp"
    compileSdk 34
    defaultConfig {
        applicationId "com.martodosko.wp"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes { debug { minifyEnabled false } }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.11.0'
}
